- name: Deploy dimanche-app-6-0727-1811 to Azure
  hosts: localhost
  gather_facts: false
  vars:
    resource_group: dimanche-grp-6
    app_name: dimanche-app-6-0727-1811
    original_app_name: dimanche-app-6
    location: francecentral
    app_repo_url: https://github.com/Nour-Ben-Hadid/nodejs-docs-hello-world.git
    app_repo_branch: main
    startup_file: ''
    default_documents: &id001
    - index.htm
    - index.html
    - index.js
    - server.js
    - app.js
  tasks:
  - name: Get Azure access token
    ansible.builtin.uri:
      url: https://login.microsoftonline.com/{{ azure_tenant }}/oauth2/v2.0/token
      method: POST
      body_format: form-urlencoded
      body:
        grant_type: client_credentials
        client_id: '{{ azure_client_id }}'
        client_secret: '{{ azure_secret }}'
        scope: https://management.azure.com/.default
    register: auth_response
  - name: Set access token fact
    ansible.builtin.set_fact:
      access_token: '{{ auth_response.json.access_token }}'
  - name: Create or update Resource Group
    ansible.builtin.uri:
      url: https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourcegroups/{{
        resource_group }}?api-version=2021-04-01
      method: PUT
      headers:
        Authorization: Bearer {{ access_token }}
        Content-Type: application/json
      body_format: json
      body:
        location: '{{ location }}'
        tags:
          Environment: Production
          CreatedBy: Ansible-Playbook
      status_code:
      - 200
      - 201
    register: rg_response
  - name: Create App Service Plan
    ansible.builtin.uri:
      url: https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{
        resource_group }}/providers/Microsoft.Web/serverfarms/{{ app_name }}-plan?api-version=2021-02-01
      method: PUT
      headers:
        Authorization: Bearer {{ access_token }}
        Content-Type: application/json
      body_format: json
      body:
        location: '{{ location }}'
        sku:
          name: F1
          tier: Free
        properties:
          name: '{{ app_name }}-plan'
      status_code:
      - 200
      - 201
    register: asp_response
  - name: Create Web App
    ansible.builtin.uri:
      url: https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{
        resource_group }}/providers/Microsoft.Web/sites/{{ app_name }}?api-version=2021-02-01
      method: PUT
      headers:
        Authorization: Bearer {{ access_token }}
        Content-Type: application/json
      body_format: json
      body:
        location: '{{ location }}'
        properties:
          serverFarmId: /subscriptions/{{ azure_subscription_id }}/resourceGroups/{{
            resource_group }}/providers/Microsoft.Web/serverfarms/{{ app_name }}-plan
          siteConfig:
            appSettings:
            - name: WEBSITE_NODE_DEFAULT_VERSION
              value: ~18
            - name: SCM_DO_BUILD_DURING_DEPLOYMENT
              value: 'true'
            - name: ENABLE_ORYX_BUILD
              value: 'true'
            - name: BUILD_FLAGS
              value: UseExpressBuild
            nodeVersion: ~18
            alwaysOn: false
      status_code:
      - 200
      - 201
    register: webapp_response
  - name: Set startup file manually
    ansible.builtin.uri:
      url: https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{
        resource_group }}/providers/Microsoft.Web/sites/{{ app_name }}/config/web?api-version=2021-02-01
      method: PATCH
      headers:
        Authorization: Bearer {{ access_token }}
        Content-Type: application/json
      body_format: json
      body:
        properties:
          appCommandLine: node {{ startup_file }}
      status_code:
      - 200
      - 201
    when: startup_file is defined and startup_file != 'auto-detect'
  - name: Verify startup file configuration
    ansible.builtin.uri:
      url: https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{
        resource_group }}/providers/Microsoft.Web/sites/{{ app_name }}/config/web?api-version=2021-02-01
      method: GET
      headers:
        Authorization: Bearer {{ access_token }}
        Content-Type: application/json
      status_code:
      - 200
    register: webapp_config_check
    when: startup_file is defined and startup_file != 'auto-detect'
  - name: Display startup file configuration status
    ansible.builtin.debug:
      msg:
      - === STARTUP FILE CONFIGURATION VERIFICATION ===
      - 'Configured startup file: {{ startup_file }}'
      - 'App Command Line: {{ webapp_config_check.json.properties.appCommandLine |
        default(''Not configured'') }}'
      - 'Node Version: {{ webapp_config_check.json.properties.nodeVersion | default(''Not
        specified'') }}'
      - "Status: {% if webapp_config_check.json.properties.appCommandLine | default('')\
        \ | length > 0 %}\u2705 Startup file successfully configured{% else %}\u274C\
        \ Startup file NOT configured{% endif %}"
    when: startup_file is defined and startup_file != 'auto-detect'
  - name: Configure deployment settings
    ansible.builtin.uri:
      url: https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{
        resource_group }}/providers/Microsoft.Web/sites/{{ app_name }}/config/web?api-version=2021-02-01
      method: PUT
      headers:
        Authorization: Bearer {{ access_token }}
        Content-Type: application/json
      body_format: json
      body:
        properties:
          numberOfWorkers: 1
          defaultDocuments: *id001
          nodeVersion: ~18
          requestTracingEnabled: true
          httpLoggingEnabled: true
          logsDirectorySizeLimit: 35
          detailedErrorLoggingEnabled: true
          publishingUsername: ${{ app_name }}
          scmType: GitHub
          webSocketsEnabled: false
          alwaysOn: false
          http20Enabled: false
          minTlsVersion: '1.2'
          ftpsState: AllAllowed
      status_code:
      - 200
      - 201
    register: webapp_config_response
  - name: Remove existing deployment source
    ansible.builtin.uri:
      url: https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{
        resource_group }}/providers/Microsoft.Web/sites/{{ app_name }}/sourcecontrols/web?api-version=2021-02-01
      method: DELETE
      headers:
        Authorization: Bearer {{ access_token }}
        Content-Type: application/json
      status_code:
      - 200
      - 204
      - 404
    register: remove_deployment_response
    ignore_errors: true
  - name: Configure deployment source (GitHub)
    ansible.builtin.uri:
      url: https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{
        resource_group }}/providers/Microsoft.Web/sites/{{ app_name }}/sourcecontrols/web?api-version=2021-02-01
      method: PUT
      headers:
        Authorization: Bearer {{ access_token }}
        Content-Type: application/json
      body_format: json
      body:
        properties:
          repoUrl: '{{ app_repo_url }}'
          branch: '{{ app_repo_branch }}'
          isManualIntegration: true
          deploymentRollbackEnabled: false
          isMercurial: false
      status_code:
      - 200
      - 201
      - 202
    register: deployment_response
  - name: Display deployment information
    ansible.builtin.debug:
      msg:
      - === WEB APP DEPLOYMENT COMPLETED SUCCESSFULLY! ===
      - 'App Name: {{ app_name }}'
      - 'Resource Group: {{ resource_group }}'
      - 'Location: {{ location }}'
      - 'App URL: https://{{ app_name }}.azurewebsites.net'
      - 'Repository: {{ app_repo_url }}'
      - 'Branch: {{ app_repo_branch }}'
      - 'Runtime: Node.js 18 on Windows'
      - 'Build System: Oryx (automatic npm install)'
      - '--- Startup Configuration ---'
      - '{% if startup_file is defined and startup_file != ''auto-detect'' %}Entry
        Point: {{ startup_file }} (manually configured){% else %}Entry Point: Auto-detection
        enabled{% endif %}'
      - 'Default Documents: {{ default_documents | join('', '') }}'
      - 'Platform: Windows Container'
      - === NEXT STEPS ===
      - 1. Check deployment status in Azure Portal
      - 2. Monitor application logs for any startup issues
      - '3. Verify app is running at: https://{{ app_name }}.azurewebsites.net'
